FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/intern2024-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080

ARG JWT_SECRET
ARG JWT_EXPIRATION_MS
ARG JWT_REFRESH_EXPIRATION_MS
ARG REDIS_PASSWORD
ARG DB_USERNAME
ARG DB_PASSWORD
ARG OPENAI_API_KEY

ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
ENV JWT_REFRESH_EXPIRATION_MS=${JWT_REFRESH_EXPIRATION_MS}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ENTRYPOINT ["java", "-jar", "app.jar"]
